theme = "base16_transparent"

[editor]
bufferline = "multiple"
auto-format = true

default-yank-register = "+"
middle-click-paste = false

completion-timeout = 5

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
