[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[colors.primary]
background = "0x0a0a0f"
foreground = "0xa9b1d6"

[font]
size = 11

[font.bold]
family = "JetBrains Mono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "P"
mods = "Control"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Control"

[window]
decorations = "None"
dynamic_padding = true

[window.padding]
x = 17
y = 17
