colors:
  primary:
    background: '#0a0a0f'
    foreground: '#a9b1d6'

  normal:
    black: '#6C5BB3'
    red: '#7462BA'
    green: '#826DC5'
    yellow: '#917AD3'
    blue: '#9F85DE'
    magenta: '#AF93EC'
    cyan: '#ad8ee6'
    white: '#989cb9'

  bright:
    black: '#6C5BB3'
    red: '#7462BA'
    green: '#826DC5'
    yellow: '#917AD3'
    blue: '#9F85DE'
    magenta: '#AF93EC'
    cyan: '#ad8ee6'
    white: '#989cb9'

window:
  padding:
    x: 17
    y: 17
  dynamic_padding: true

  decorations: 'None'


font:
  normal:
    family: JetBrains Mono
    style: Regular

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: Italic

  bold_italic:
    family: JetBrains Mono
    style: Bold Italic

  size: 11

key_bindings:
  - { key: P, mods: Control, action: SpawnNewInstance }
  - { key: K, mods: Control, action: ClearHistory }
