vim.cmd[[luafile $HOME/.config/nvim/setups/options.lua]]
vim.cmd[[luafile $HOME/.config/nvim/setups/keymap.lua]]
vim.cmd[[luafile $HOME/.config/nvim/setups/cmds.lua]]
vim.cmd[[luafile $HOME/.config/nvim/setups/packages.lua]]
vim.cmd[[luafile $HOME/.config/nvim/setups/theme.lua]]
vim.cmd[[luafile $HOME/.config/nvim/setups/pluginscfg.lua]]
vim.cmd[[luafile $HOME/.config/nvim/setups/lsps.lua]]
